app = "Portfólio"  
region = "gru"  
organization = "jricardogoulart"  

[[builds]]
  image = "docker://python:3.11.2"  
  dockerfile = "Dockerfile"  # Se você usar um Dockerfile personalizado, especifique o caminho aqui

[build]
  publish = "."  

[env]
  PORT = 5000  # Porta interna em que o Flask está ouvindo

[[services]]
  internal_port = 5000  # Porta interna em que o Flask está ouvindo

[[services.ports]]
  handlers = ["http"]
  port = 80  # Porta externa que receberá solicitações HTTP

[[deploy.targets]]
  name = "production"
  organization = "jricardogoulart"  # Substitua "suaorganizacao" pelo nome da sua organização

[deploy]
  release_command = "gunicorn -b 0.0.0.0:$PORT yourapp:app.py"  